### like to article
PUT localhost:8080/api/v1/article_like/private/like/c6186a73-e060-410a-ac1a-1d358ec94a0b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA

### dislike to article
PUT localhost:8080/api/v1/article_like/private/dislike/c6186a73-e060-410a-ac1a-1d358ec94a0b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA


### remove
DELETE localhost:8080/api/v1/article_like/private/delete/c6186a73-e060-410a-ac1a-1d358ec94a0b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA
