### create article
POST localhost:8080/api/v1/article/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTE4NjIsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjQ3ODI2MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.gaYW_QMQBAgWwuatkrNoUzhE7o5ThIZNW5zxb4avKORAte_J6f-bfws8_woC7orYnjTazsDyWdj0G632B5HyZQ
Content-Type: application/json

{
  "title": "Foundation course",
  "description":"Brain academyda java kurslari ochilyapti",
  "content": "Hazillashgandek",
  "categoryId": 1,
  "regionId": 1
}

### update article

POST localhost:8080/api/v1/article/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTE4NjIsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjQ3ODI2MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.gaYW_QMQBAgWwuatkrNoUzhE7o5ThIZNW5zxb4avKORAte_J6f-bfws8_woC7orYnjTazsDyWdj0G632B5HyZQ
Content-Type: application/json

{
  "title": "Foundation course",
  "description": "Brain academyda java kurslari ochilyapti",
  "content": "Hazillashgandek Mazgi",
  "categoryId": 1,
  "regionId": 1,
  "typeId": 1,
  "imageId": 1,
  "visible": true
}

### delete article update visible to false
DELETE localhost:8080/api/v1/article/delete/36f7ea3a-16be-467e-bf4a-ac3f1338336a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTE4NjIsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjQ3ODI2MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.gaYW_QMQBAgWwuatkrNoUzhE7o5ThIZNW5zxb4avKORAte_J6f-bfws8_woC7orYnjTazsDyWdj0G632B5HyZQ

### change status by publisher published not published
PUT localhost:8080/api/v1/article/adm/346c3746-b3e7-4df3-b888-36b9ae655aa4?status = PUBLISHED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzOTUzNzgsImlkIjoxNCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTY4MjQ4MTc3OCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.AoH3U7jRhZk_3Q0q-HjOeTKTT5Kn_YpTbj-E-LWcJmtvVjso1w_9Ecco03QsRJjv-QOq3hOoI84wYtDHAWkGbw

###  Get Last 5 Article By Types  ordered_by_created_date
###        (Berilgan types bo'yicha oxirgi 5ta pubished bo'lgan article ni return qiladi.)
###       ArticleShortInfo
GET localhost:8080/api/v1/article/public/type/3/1


