### create article
### moder eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA
### pub eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgxODcsImVtYWlsIjoiZWxtdXJvZDJAbWFpbC5ydSIsInJvbGUiOiJST0xFX1BVQkxJU0hFUiIsImV4cCI6MTY4NDc1NDU4NywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.yV22amr_T3c4M0pQ1e0vjwplu3A82eYRl5ukWstDFslgb3Xjk-W0eaDv8-YtV13_bmInZdcGuiv8Z-0MPv3o6A
### admin eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NTc5MjYsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODU1MjE5MjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.vHoB7DH10zHt4F771ixv5tD2douPtfsM95Q-qGjiFE-_p30PfuYlLpweEbFziJLSQlTEhf24WuBOD2aMrgjTEg
POST localhost:8080/api/v1/article/private/moder/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA
Content-Type: application/json

{
  "title": "Title 2 titlt tltlttltlt",
  "description": "Description 1 description",
  "content": "content 1 jkwsdh salsdacjm sdjh",
  "categoryId": 1,
  "regionId": 1,
  "typeId": 1
}

### update article

POST localhost:8080/api/v1/article/private/moder/update/95d44b63-34fc-41a4-9423-af32d13c93fd
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA
Content-Type: application/json

{
  "title": "Spring course",
  "description": "Brain academyda java kurslari ochilyapti",
  "content": "Contenttttttttttttttttttttttttt",
  "categoryId": 1,
  "regionId": 1,
  "typeId": 1,
  "imageId": 1,
  "visible": true
}

### delete article update visible to false
DELETE localhost:8080/api/v1/article/private/moder/delete/95d44b63-34fc-41a4-9423-af32d13c93fd
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgyNzYsImVtYWlsIjoiZWxtdXJvZDNAbWFpbC5ydSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTY4NDc1NDY3NiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.o9CeAfU2KyXkaOUwJ8Ta4GgOE0FNHLtcfgHE7_MvVP9ynNUOLvcD7t3mpNzHWP6nhryeC_iVJAfDvGVtPHdlyA

###Change status by id (PUBLISHER) (publish,not_publish)
PUT localhost:8080/api/v1/article/private/pub/publish/c6186a73-e060-410a-ac1a-1d358ec94a0b?status = PUBLISHED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NjgxODcsImVtYWlsIjoiZWxtdXJvZDJAbWFpbC5ydSIsInJvbGUiOiJST0xFX1BVQkxJU0hFUiIsImV4cCI6MTY4NDc1NDU4NywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.yV22amr_T3c4M0pQ1e0vjwplu3A82eYRl5ukWstDFslgb3Xjk-W0eaDv8-YtV13_bmInZdcGuiv8Z-0MPv3o6A


###  Get Last 5 Article By Types  ordered_by_created_date
GET localhost:8080/api/v1/article/public/publish/5/1


### Get Last 3 Article By Types  ordered_by_created_date
GET localhost:8080/api/v1/article/public/publish/3/1


### get top 8 included id list
POST localhost:8080/api/v1/article/public/publish/8
Content-Type: application/json

{
 "idList": ["c6186a73-e060-410a-ac1a-1d358ec94a0b",2,3]
}


### Get Article By Id And Lang
GET localhost:8080/api/v1/article/public/publish/lang?id=c6186a73-e060-410a-ac1a-1d358ec94a0b
Accept-Language:en

###  Get Last 4 Article By Types and except(shu article id dan farqli bolgan) given article id.
GET localhost:8080/api/v1/article/public/publish/4?articleId=c616a73-e060-410a-ac1a-1d358ec94a0b&typeId=1


### Get 4 most read articles
GET localhost:8080/api/v1/article/public/publish/top/4

### Get Last 4 Article By TagName (Bitta article ni eng ohirida chiqib turadi.)
GET localhost:8080/api/v1/article/public/publish/tag/Dunyo


###Get Last 5 Article By Types  And By Region Key
GET localhost:8080/api/v1/article/public/publish/region/5?regionId=1&typeId=2


###Get Article list by Region Key (Pagination)
GET localhost:8080/api/v1/article/public/publish/region?regionId=1&page=2&size=2

### Get Last 5 Article Category Key
GET localhost:8080/api/v1/article/public/publish/category/5/2

### Get Article By Category Key (Pagination)
GET localhost:8080/api/v1/article/public/publish/category?categoryId=2&size=2

### Increase Article View Count by Article Id
PUT localhost:8080/api/v1/article/public/view_count/dc9c0983-7e3e-4144-b950-6b051ab2ac8f


### Increase Article Share  Count by Article Id
PUT localhost:8080/api/v1/article/public/share_count/dc9c0983-7e3e-4144-b950-6b051ab2ac8f

### filter
POST localhost:8080/api/v1/article/public/publish/filter
Content-Type: application/json

{
  "regionId": 1
}
