### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Elmurod",
  "surname": "Saydaliyev",
  "phone": "900055072",
  "email": "saydaliyevelmurod01@gmail.com",
  "password": "123456"
}