### create category only by admin
POST localhost:8080/api/v1/category/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1NjI1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0MjY1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.0T7tdEdYb6WutOuEC_Gl_kHJrw692aWVoOfdI25igc69SujJLkevcuKVTDgD_9lSiUfc5Ij_m7wWNb6MreP_MA
Content-Type: application/json

{
  "nameUz": "O'zbekiston1 ",
  "nameRu": "Узбекистан1",
  "nameEn": "Uzbekistan1"
}
### update by id only by admin
POST localhost:8080/api/v1/category/private/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1NjI1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0MjY1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.0T7tdEdYb6WutOuEC_Gl_kHJrw692aWVoOfdI25igc69SujJLkevcuKVTDgD_9lSiUfc5Ij_m7wWNb6MreP_MA
Content-Type: application/json

{
  "nameUz":"O'zbekiston"
}

### delete by id only admin
DELETE localhost:8080/api/v1/category/private/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1NjI1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0MjY1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.0T7tdEdYb6WutOuEC_Gl_kHJrw692aWVoOfdI25igc69SujJLkevcuKVTDgD_9lSiUfc5Ij_m7wWNb6MreP_MA

### get list only by admin with pagination
GET localhost:8080/api/v1/category/private/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1NjI1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0MjY1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.0T7tdEdYb6WutOuEC_Gl_kHJrw692aWVoOfdI25igc69SujJLkevcuKVTDgD_9lSiUfc5Ij_m7wWNb6MreP_MA

### get list by name  only by id with pagination
GET localhost:8080/api/v1/category/private/list/ru?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1NjI1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0MjY1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.0T7tdEdYb6WutOuEC_Gl_kHJrw692aWVoOfdI25igc69SujJLkevcuKVTDgD_9lSiUfc5Ij_m7wWNb6MreP_MA



