### create profile

POST localhost:8080/api/v1/profile
Content-Type:  application/json

{
  "name": "ADMIN",
  "surname": "ADMIN",
  "email": "admin@mail.ru",
  "phone": "1213",
  "password": "123456",
  "role": "ADMIN"
}