### create tag
POST localhost:8080/api/v1/tag/private/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MjE1MjIsImlkIjo1LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODQ0ODU1MjIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.364y0KHoQFRho3YxSwps984dQX7mfHH9QkjgM7VcWQvPo-smhCYIiNs_Zkdlb2DZjjSrKvTqJVrAPiN-OVSe7w
Content-Type: application/json

{
  "name": "RossiyavsUkraina"
}

### update tag by id
POST localhost:8080/api/v1/tag/private/update/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MjAzMDcsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4NDQ4NDMwNywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.48bHv_641Np3i62_zKFp263rIJrr2ZNmfnFZozKgLMlpSssdmG0xZgz7m8tYJtCuq4WfDQ2NZzCsafeZrGE0Ew
Content-Type: application/json

{
  "name": "Dunyo"
}

### delete by id

DELETE localhost:8080/api/v1/tag/private/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MjAzMDcsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4NDQ4NDMwNywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.48bHv_641Np3i62_zKFp263rIJrr2ZNmfnFZozKgLMlpSssdmG0xZgz7m8tYJtCuq4WfDQ2NZzCsafeZrGE0Ew


### get list
GET localhost:8080/api/v1/tag/private/list?page=2&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MjAzMDcsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4NDQ4NDMwNywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.48bHv_641Np3i62_zKFp263rIJrr2ZNmfnFZozKgLMlpSssdmG0xZgz7m8tYJtCuq4WfDQ2NZzCsafeZrGE0Ew


### addd tag to article
POST localhost:8080/api/v1/tag/private/tag?a_id=dc9c0983-7e3e-4144-b950-6b051ab2ac8f&t_id=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2MjAzMDcsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4NDQ4NDMwNywiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.48bHv_641Np3i62_zKFp263rIJrr2ZNmfnFZozKgLMlpSssdmG0xZgz7m8tYJtCuq4WfDQ2NZzCsafeZrGE0Ew
